name: aareguru_api
description: A wrapper for the Aare.guru API
version: 0.1.0+1
repository: https://github.com/Wii42/aareguru_api_dart_wrapper

environment:
  sdk: ^3.4.3

dependencies:
    http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
