name: aareguru_api
description: Unofficial type-safe Dart wrapper for the Aare.guru API. Aare.guru provides infos about bathing spots in the Aare river in Switzerland.
version: 0.3.1
repository: https://github.com/Wii42/aareguru_api_dart_wrapper

environment:
  sdk: ^3.4.3

dependencies:
    http: ^1.2.2
    latlong2: ^0.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
